# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIIebnUWiJg16B5JXcxgmOCZipCGv-R9
"""

print('Halo Dunia')